# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'Node.js CI'

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: 'actions/checkout@v2'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: 'actions/setup-node@v2.1.5'
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Cache dependencies'
        uses: 'actions/cache@v2.1.5'
        with:
          path: '.npm'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - run: 'npm ci --cache .npm --prefer-offline'
      - run: 'npm run lint:commit -- --to "${{ github.sha }}"'
      - run: 'npm run lint:docker'
      - run: 'npm run lint:editorconfig'
      - run: 'npm run lint:markdown'
      - run: 'npm run lint:typescript'
      - run: 'npm run build'
      - run: 'npm run test'
